version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: verza-postgres
    environment:
      POSTGRES_USER: verza
      POSTGRES_PASSWORD: verza
      POSTGRES_DB: verza
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: verza-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

  minio:
    image: minio/minio:latest
    container_name: verza-minio
    environment:
      MINIO_ROOT_USER: verza
      MINIO_ROOT_PASSWORD: verzaverza
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata: {}
  minio_data: {}