// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkUpdateCredentialStatus(ctx context.Context, arg BulkUpdateCredentialStatusParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateKYCJob(ctx context.Context, arg CreateKYCJobParams) (KycJob, error)
	CreateRevocation(ctx context.Context, arg CreateRevocationParams) (Revocation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]AuditLog, error)
	GetAuditLogsByAction(ctx context.Context, arg GetAuditLogsByActionParams) ([]AuditLog, error)
	GetAuditLogsByObject(ctx context.Context, arg GetAuditLogsByObjectParams) ([]AuditLog, error)
	GetAuditLogsByTimeRange(ctx context.Context, arg GetAuditLogsByTimeRangeParams) ([]AuditLog, error)
	GetCredential(ctx context.Context, id pgtype.UUID) (Credential, error)
	GetCredentialByHash(ctx context.Context, vcHash []byte) (Credential, error)
	GetCredentialStats(ctx context.Context) (GetCredentialStatsRow, error)
	GetCredentialsByDateRange(ctx context.Context, arg GetCredentialsByDateRangeParams) ([]Credential, error)
	GetCredentialsByIssuer(ctx context.Context, arg GetCredentialsByIssuerParams) ([]Credential, error)
	GetCredentialsBySubject(ctx context.Context, subjectDid string) ([]Credential, error)
	GetCredentialsByType(ctx context.Context, arg GetCredentialsByTypeParams) ([]Credential, error)
	GetCredentialsForRevocation(ctx context.Context, revokedAt *time.Time) ([]Credential, error)
	GetExpiredCredentials(ctx context.Context) ([]Credential, error)
	GetKYCJob(ctx context.Context, id pgtype.UUID) (KycJob, error)
	GetKYCJobsByUser(ctx context.Context, userID pgtype.UUID) ([]KycJob, error)
	GetKYCStats(ctx context.Context) (GetKYCStatsRow, error)
	GetRevocation(ctx context.Context, vcHash []byte) (Revocation, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByDID(ctx context.Context, did string) (User, error)
	GetUserStats(ctx context.Context) (GetUserStatsRow, error)
	ListKYCJobs(ctx context.Context, arg ListKYCJobsParams) ([]KycJob, error)
	ListRevocations(ctx context.Context, arg ListRevocationsParams) ([]Revocation, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokeCredential(ctx context.Context, vcHash []byte) error
	SearchCredentials(ctx context.Context, arg SearchCredentialsParams) ([]Credential, error)
	UpdateCredentialAnchor(ctx context.Context, arg UpdateCredentialAnchorParams) error
	UpdateKYCJobStatus(ctx context.Context, arg UpdateKYCJobStatusParams) error
	UpdateUserLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateUserRiskScore(ctx context.Context, arg UpdateUserRiskScoreParams) error
}

var _ Querier = (*Queries)(nil)
