export const MOCK_DATA = {
  escrow: {
    initiate: {
      escrow_id: 'escrow_30a52kdfj25',
      status: 'pending',
      amount: 25.00,
      currency: 'HBAR',
      created_at: new Date().toISOString(),
    }
  },
  
  verification: {
    status: {
      escrowId: 'escrow_123456789',
      status: 'in_progress', // 'submitted' | 'in_progress' | 'completed' | 'failed'
      steps: [
        {
          id: '1',
          label: 'Documents Uploaded',
          status: 'completed',
          timestamp: new Date().toLocaleString(),
        },
        {
          id: '2', 
          label: 'Identity Verification',
          status: 'active',
          timestamp: null
        },
        {
          id: '3',
          label: 'Final Review',
          status: 'pending',
          timestamp: null
        }
      ],
      estimatedCompletion: '2-3 minutes'
    },
    
    results: {
      status: 'verified',
      credentialId: 'cred_380439ad324jd',
      vcDetails: {
        id: 'vc_90ab5678cde5f12678ae34',
        issuer: 'TechCorp Solutions',
        issuedDate: new Date().toLocaleString(),
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toLocaleString(),
        type: 'Identity Verification',
        proofHash: '0xa7f8cf12de92e1b3d4567890a2345bc90abc16783456789345670abcdef12'
      }
    }
  },

  verifiers: [
    {
      id: "1",
      name: "TechCorp\nSolutions",
      type: "Enterprise",
      rating: 4.8,
      verified: 1240,
      logo: "shield-check",
      status: "active" as const,
      description: "Leading technology verification provider",
    },
    {
      id: "2",
      name: "SecureID Pro",
      type: "Financial",
      rating: 4.9,
      verified: 856,
      logo: "shield",
      status: "active" as const,
      description: "Banking and financial services verification",
    },
    {
      id: "3",
      name: "VerifyTech\nSystems",
      type: "Healthcare",
      rating: 4.7,
      verified: 2134,
      logo: "shield-check",
      status: "active" as const,
      description: "Medical and healthcare credential verification",
    },
    {
      id: "4",
      name: "GlobalCheck",
      type: "Government",
      rating: 4.6,
      verified: 3421,
      logo: "shield",
      status: "active" as const,
      description: "Government document verification services",
    },
    {
      id: "5",
      name: "EduVerify",
      type: "Education",
      rating: 4.8,
      verified: 1876,
      logo: "shield-check",
      status: "active" as const,
      description: "Academic credentials and diploma verification",
    },
    {
      id: "6",
      name: "CryptoAuth",
      type: "Blockchain",
      rating: 4.9,
      verified: 756,
      logo: "shield",
      status: "active" as const,
      description: "Blockchain-based identity verification",
    },
    {
      id: "7",
      name: "LegalVerify\nPro",
      type: "Legal",
      rating: 4.5,
      verified: 943,
      logo: "shield-check",
      status: "active" as const,
      description: "Legal document and bar certification verification",
    },
    {
      id: "8",
      name: "BiometricID",
      type: "Biometric",
      rating: 4.7,
      verified: 2567,
      logo: "shield",
      status: "active" as const,
      description: "Advanced biometric identity verification",
    },
    {
      id: "9",
      name: "CloudVerify",
      type: "Cloud",
      rating: 4.6,
      verified: 1543,
      logo: "shield-check",
      status: "active" as const,
      description: "Cloud-based verification infrastructure",
    },
    {
      id: "10",
      name: "MobileID\nSolutions",
      type: "Mobile",
      rating: 4.4,
      verified: 2876,
      logo: "shield",
      status: "active" as const,
      description: "Mobile device identity verification",
    },
    {
      id: "11",
      name: "InsuranceCheck",
      type: "Insurance",
      rating: 4.7,
      verified: 1234,
      logo: "shield-check",
      status: "active" as const,
      description: "Insurance policy and claim verification",
    },
    {
      id: "12",
      name: "RealEstateID",
      type: "Real Estate",
      rating: 4.5,
      verified: 987,
      logo: "shield",
      status: "active" as const,
      description: "Property and real estate verification services",
    },
    {
      id: "13",
      name: "RetailVerify",
      type: "Retail",
      rating: 4.3,
      verified: 3456,
      logo: "shield-check",
      status: "active" as const,
      description: "Retail customer verification platform",
    },
    {
      id: "14",
      name: "MediaAuth",
      type: "Media",
      rating: 4.6,
      verified: 1765,
      logo: "shield",
      status: "active" as const,
      description: "Media content and journalist verification",
    },
    {
      id: "15",
      name: "SportsID\nPro",
      type: "Sports",
      rating: 4.8,
      verified: 654,
      logo: "shield-check",
      status: "active" as const,
      description: "Athletic and sports credential verification",
    },
    {
      id: "16",
      name: "TravelVerify",
      type: "Travel",
      rating: 4.4,
      verified: 2345,
      logo: "shield",
      status: "active" as const,
      description: "Travel document and visa verification",
    },
    {
      id: "17",
      name: "NGOCheck",
      type: "Non-Profit",
      rating: 4.7,
      verified: 876,
      logo: "shield-check",
      status: "active" as const,
      description: "Non-profit organization verification",
    },
    {
      id: "18",
      name: "StartupID",
      type: "Startup",
      rating: 4.2,
      verified: 1432,
      logo: "shield",
      status: "active" as const,
      description: "Startup and entrepreneur verification",
    },
    {
      id: "19",
      name: "AgriVerify",
      type: "Agriculture",
      rating: 4.5,
      verified: 567,
      logo: "shield-check",
      status: "active" as const,
      description: "Agricultural certification verification",
    },
    {
      id: "20",
      name: "EnergyID\nSystems",
      type: "Energy",
      rating: 4.6,
      verified: 789,
      logo: "shield",
      status: "active" as const,
      description: "Energy sector credential verification",
    },
    {
      id: "21",
      name: "PlantCheck",
      type: "Manufacturing",
      rating: 4.4,
      verified: 2109,
      logo: "shield-check",
      status: "active" as const,
      description: "Manufacturing quality and safety verification",
    },
    {
      id: "22",
      name: "ArtVerify",
      type: "Arts",
      rating: 4.7,
      verified: 432,
      logo: "shield",
      status: "active" as const,
      description: "Art authentication and provenance verification",
    },
    {
      id: "23",
      name: "TransportID",
      type: "Transportation",
      rating: 4.3,
      verified: 1876,
      logo: "shield-check",
      status: "active" as const,
      description: "Transportation and logistics verification",
    },
    {
      id: "24",
      name: "ConstructVerify",
      type: "Construction",
      rating: 4.5,
      verified: 1345,
      logo: "shield",
      status: "active" as const,
      description: "Construction certification and safety verification",
    },
    {
      id: "25",
      name: "FoodSafetyID",
      type: "Food Safety",
      rating: 4.8,
      verified: 2567,
      logo: "shield-check",
      status: "active" as const,
      description: "Food safety and quality certification verification",
    },
    {
      id: "26",
      name: "PharmVerify",
      type: "Pharmaceutical",
      rating: 4.9,
      verified: 987,
      logo: "shield",
      status: "active" as const,
      description: "Pharmaceutical licensing and drug verification",
    },
    {
      id: "27",
      name: "TechSkills\nVerify",
      type: "Technology",
      rating: 4.6,
      verified: 3210,
      logo: "shield-check",
      status: "active" as const,
      description: "Technical skills and certification verification",
    },
    {
      id: "28",
      name: "ElectronicsID",
      type: "Electronics",
      rating: 4.4,
      verified: 1654,
      logo: "shield",
      status: "active" as const,
      description: "Electronics component authentication",
    },
    {
      id: "29",
      name: "TextileVerify",
      type: "Textile",
      rating: 4.2,
      verified: 789,
      logo: "shield-check",
      status: "active" as const,
      description: "Textile quality and origin verification",
    },
    {
      id: "30",
      name: "ChemicalCheck",
      type: "Chemical",
      rating: 4.7,
      verified: 543,
      logo: "shield",
      status: "active" as const,
      description: "Chemical safety and compliance verification",
    },
    {
      id: "31",
      name: "AutoVerify\nPro",
      type: "Automotive",
      rating: 4.5,
      verified: 2876,
      logo: "shield-check",
      status: "active" as const,
      description: "Automotive parts and vehicle verification",
    },
    {
      id: "32",
      name: "WasteManageID",
      type: "Environmental",
      rating: 4.6,
      verified: 1234,
      logo: "shield",
      status: "active" as const,
      description: "Environmental compliance verification",
    },
    {
      id: "33",
      name: "SupplyChainID",
      type: "Supply Chain",
      rating: 4.8,
      verified: 1987,
      logo: "shield-check",
      status: "active" as const,
      description: "Supply chain transparency verification",
    },
    {
      id: "34",
      name: "CosmeticVerify",
      type: "Cosmetics",
      rating: 4.3,
      verified: 765,
      logo: "shield",
      status: "active" as const,
      description: "Cosmetic safety and ingredient verification",
    },
    {
      id: "35",
      name: "JewelryAuth",
      type: "Jewelry",
      rating: 4.7,
      verified: 456,
      logo: "shield-check",
      status: "active" as const,
      description: "Precious metal and gemstone authentication",
    },
    {
      id: "36",
      name: "Mine Lans",
      type: "Mining",
      rating: 4.4,
      verified: 678,
      logo: "shield",
      status: "active" as const,
      description: "Mining safety and certification verification",
    },
    {
      id: "37",
      name: "Teleco",
      type: "Telecom",
      rating: 4.5,
      verified: 2345,
      logo: "shield-check",
      status: "active" as const,
      description: "Telecommunications equipment verification",
    }
  ],


}